// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWabinyxifqwfqheUAhTr_YtqRogIUpbs',
    appId: '1:821718222333:web:fd6f636e32cf07cc7b0594',
    messagingSenderId: '821718222333',
    projectId: 'mobile-flutter-firebase',
    authDomain: 'mobile-flutter-firebase.firebaseapp.com',
    storageBucket: 'mobile-flutter-firebase.appspot.com',
    measurementId: 'G-BJSZSHF0RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPbiBfvtxglJXtDVsgXJVSR8xKp5gYLfM',
    appId: '1:821718222333:android:e3a1e11551e41f507b0594',
    messagingSenderId: '821718222333',
    projectId: 'mobile-flutter-firebase',
    storageBucket: 'mobile-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFdBmx0sQlXcPEWY2e8ih39ajSBziFnBM',
    appId: '1:821718222333:ios:df19f87cf02144d87b0594',
    messagingSenderId: '821718222333',
    projectId: 'mobile-flutter-firebase',
    storageBucket: 'mobile-flutter-firebase.appspot.com',
    iosClientId: '821718222333-kk9p2kiv2gg865i9gski3vnr0v8clmka.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFdBmx0sQlXcPEWY2e8ih39ajSBziFnBM',
    appId: '1:821718222333:ios:df19f87cf02144d87b0594',
    messagingSenderId: '821718222333',
    projectId: 'mobile-flutter-firebase',
    storageBucket: 'mobile-flutter-firebase.appspot.com',
    iosClientId: '821718222333-kk9p2kiv2gg865i9gski3vnr0v8clmka.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileFlutterFirebase',
  );
}
